---

- name: Install unattended-upgrades package
  ansible.builtin.package:
    name: "unattended-upgrades"
    state: present
  become: true
  become_user: root

- name: Adjust APT update intervals
  ansible.builtin.copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
    mode: "0644"
    owner: root
    group: root
  become: true
  become_user: root

- name: Configure automatic updates on ubuntu client systems
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\/\/\s*"\${distro_id}:\${distro_codename}-updates";'
    line: '        "${distro_id}:${distro_codename}-updates";'
  when:
    - ansible_distribution == 'Ubuntu'
    - "'client' in group_names"
  become: true
  become_user: root

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  become: true
  become_user: root
